spring:
  # ???????
  datasource:
    url: jdbc:mysql://1.15.98.165:6033/haha?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: HBQinjie123!
    # ???
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # ????????
      initial-size: 8
      # ?????
      max-active: 16
      # ?????
      min-idle: 1
      # ??????
      max-wait: 60000

# mybatis配置
mybatis:
  check-config-location: true
  #  指定mybatis的配置文件(将mybatis配置文件复到resources目录下mybatis中根据自己的需求在mybatis配置文件中添加自己的配置)
  config-location: classpath:mybatis/mybatis-config.xml
  #  ??xml??
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  #  ??model???
  type-aliases-package: "com.example.awesomespring.dao.entity.*"

# ????
logging:
  pattern:
    # ??????
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(%5p) [%thread] %clr(%logger){cyan} : %msg%n"
  level:
    #    trace < debug < info < warn < error < fatal
    # ??????
    root: info
    # ???????
    com.example.awesomespring: warn

