server:
  port: 9031
  servlet:
    context-path: /code-mybatis/

spring:
  # 数据源
  datasource:

    # ???
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # ????????
      initial-size: 8
      # ?????
      max-active: 16
      # ?????
      min-idle: 1
      # ??????
      max-wait: 60000

# mybatis配置
mybatis:
  check-config-location: true
  #  指定mybatis的配置文件(将mybatis配置文件复到resources目录下mybatis中根据自己的需求在mybatis配置文件中添加自己的配置)
  config-location: classpath:/mybatis/mybatis-config.xml
  #  ??xml??
  mapper-locations: classpath:/mybatis/mapper/*Mapper.xml
  #  ??model???
#  type-aliases-package: com.lishijiee.awesomespring.dao.entity.*
